### ISSUE TITLE
Ordering of the radii and filling vectors

### ISSUE THREAD

**Issue by sbadrian** [HoBeZwe/SphericalScattering.jl#19]
Currently,  the elements of the radii and the filling vectors of the LayeredSphere and LayeredSpherePEC are ordered starting with the outermost layer. This is counterintuitive in that we start in our pictures with the innermost layer.

In order to match our descriptions, I would reverse the ordering. The are only little changes to the existing code necessary.

**Comment by HoBeZwe** [comment]
I very much agree. With the new version, the ordering is reversed and fits now the images in the documentation.
